### ISSUE TITLE
KizuAPI rewrite

### ISSUE THREAD

**Issue by LichKing112** [TheRealKizu/Alaia#37]
#### What type of issue is this?

- [ ] Bug Report
- [x] Feature Request

#### Describe the issue:
- As the title says, Me rewrite Kizu's shitty API because he told me to.

#### Steps to reproduce [Bug Report only]: 
- *INSERT STEPS*

#### Expected behavior [Bug Report only]: 
- *INSERT DESCRIPTION*

#### System Information:

* OS: Linux Ubuntu 18.04
* Node Version: v15.14.0

**Comment by TheRealKizu** [comment]
Nazi mf
